coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true
